# Generated by Django 5.1.4 on 2025-01-17 18:14

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntitle', models.CharField(max_length=100)),
                ('ndesc', tinymce.models.HTMLField()),
            ],
        ),
    ]
